DO $$
BEGIN
  -- Create storage bucket if it doesn't exist
  INSERT INTO storage.buckets (id, name, public)
  VALUES ('dados_brutos', 'dados_brutos', true)
  ON CONFLICT (id) DO NOTHING;

  -- Ensure modelos table matches requirements
  CREATE TABLE IF NOT EXISTS public.modelos (
    id_mod integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    id_fonte integer REFERENCES public.fonte_agua(id_fonte) ON DELETE CASCADE,
    cenario character varying,
    estrategia character varying,
    arq_mod text,
    arq_perdas text,
    arq_demanda text,
    arq_capex_estrategias text,
    arq_capex_perdas text,
    arq_opex text
  );

  -- Ensure indicadores_aplicado table matches requirements
  CREATE TABLE IF NOT EXISTS public.indicadores_aplicado (
    id_ia integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    id_s integer REFERENCES public.simulacao_ssd(id_s) ON DELETE CASCADE,
    id_indicador integer REFERENCES public.indicadores(id_indicador) ON DELETE CASCADE,
    arquivo character varying
  );

END $$;

-- Enable RLS
ALTER TABLE public.modelos ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.indicadores_aplicado ENABLE ROW LEVEL SECURITY;

-- Drop existing policies if any
DROP POLICY IF EXISTS "modelos_all" ON public.modelos;
DROP POLICY IF EXISTS "indicadores_aplicado_all" ON public.indicadores_aplicado;

-- Create full access RLS policies for authenticated users
CREATE POLICY "modelos_all" ON public.modelos
  FOR ALL TO authenticated USING (true) WITH CHECK (true);

CREATE POLICY "indicadores_aplicado_all" ON public.indicadores_aplicado
  FOR ALL TO authenticated USING (true) WITH CHECK (true);

-- Storage bucket policies for dados_brutos
DROP POLICY IF EXISTS "dados_brutos_public_read" ON storage.objects;
CREATE POLICY "dados_brutos_public_read" ON storage.objects
  FOR SELECT TO public USING (bucket_id = 'dados_brutos');

DROP POLICY IF EXISTS "dados_brutos_auth_insert" ON storage.objects;
CREATE POLICY "dados_brutos_auth_insert" ON storage.objects
  FOR INSERT TO authenticated WITH CHECK (bucket_id = 'dados_brutos');

DROP POLICY IF EXISTS "dados_brutos_auth_update" ON storage.objects;
CREATE POLICY "dados_brutos_auth_update" ON storage.objects
  FOR UPDATE TO authenticated USING (bucket_id = 'dados_brutos') WITH CHECK (bucket_id = 'dados_brutos');

DROP POLICY IF EXISTS "dados_brutos_auth_delete" ON storage.objects;
CREATE POLICY "dados_brutos_auth_delete" ON storage.objects
  FOR DELETE TO authenticated USING (bucket_id = 'dados_brutos');
