DO $$
BEGIN

-- Tabela: fonte_agua
CREATE TABLE IF NOT EXISTS public.fonte_agua (
  id_fonte INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  nome_fonte VARCHAR(30),
  sujeito_perdas BOOLEAN DEFAULT true
);

-- Tabela: tipos_cenarios
CREATE TABLE IF NOT EXISTS public.tipos_cenarios (
  id_tc INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  descricao VARCHAR(20),
  obs_tipo_cenario VARCHAR(100)
);

-- Tabela: cenarios
CREATE TABLE IF NOT EXISTS public.cenarios (
  id_cenarios INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  cenarios VARCHAR(30),
  obs_cenario VARCHAR(255)
);

-- Tabela: estrategias
CREATE TABLE IF NOT EXISTS public.estrategias (
  id_estrategia INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  descricao VARCHAR(20),
  obs_estrategia VARCHAR(100)
);

-- Tabela: simulacao_ssd
CREATE TABLE IF NOT EXISTS public.simulacao_ssd (
  id_s INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  descricao VARCHAR(255)
);

-- Tabela: cenarios_fonte
CREATE TABLE IF NOT EXISTS public.cenarios_fonte (
  id_cf INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  id_fonte INTEGER REFERENCES public.fonte_agua(id_fonte) ON DELETE CASCADE,
  id_tc INTEGER REFERENCES public.tipos_cenarios(id_tc) ON DELETE CASCADE
);

-- Tabela: estrategias_fonte
CREATE TABLE IF NOT EXISTS public.estrategias_fonte (
  id_ef INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  id_fonte INTEGER REFERENCES public.fonte_agua(id_fonte) ON DELETE CASCADE,
  id_e INTEGER REFERENCES public.estrategias(id_estrategia) ON DELETE CASCADE
);

-- Tabela: cenario_simulacao
CREATE TABLE IF NOT EXISTS public.cenario_simulacao (
  id_cs INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  id_s INTEGER REFERENCES public.simulacao_ssd(id_s) ON DELETE CASCADE,
  id_fonte INTEGER REFERENCES public.fonte_agua(id_fonte) ON DELETE CASCADE,
  id_tc INTEGER REFERENCES public.tipos_cenarios(id_tc) ON DELETE CASCADE,
  id_c INTEGER REFERENCES public.cenarios(id_cenarios) ON DELETE CASCADE,
  id_e INTEGER REFERENCES public.estrategias(id_estrategia) ON DELETE CASCADE
);

-- Tabela: cenario_demanda
CREATE TABLE IF NOT EXISTS public.cenario_demanda (
  id_cd INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  nome_cenario_demanda VARCHAR(30),
  descricao VARCHAR(100)
);

-- Tabela: cenario_consumo
CREATE TABLE IF NOT EXISTS public.cenario_consumo (
  id_cc INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  nome_cenario_consumo VARCHAR(30),
  descricao VARCHAR(100)
);

-- Tabela: cenario_perdas
CREATE TABLE IF NOT EXISTS public.cenario_perdas (
  id_cp INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  nome_cenario_perdas VARCHAR(30),
  descricao VARCHAR(100)
);

-- Tabela: dados_simulacao
CREATE TABLE IF NOT EXISTS public.dados_simulacao (
  id_ds INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  id_s INTEGER REFERENCES public.simulacao_ssd(id_s) ON DELETE CASCADE,
  tempo VARCHAR(7),
  id_fonte INTEGER REFERENCES public.fonte_agua(id_fonte) ON DELETE CASCADE,
  id_tc INTEGER REFERENCES public.tipos_cenarios(id_tc) ON DELETE CASCADE,
  id_c INTEGER REFERENCES public.cenarios(id_cenarios) ON DELETE CASCADE,
  id_e INTEGER REFERENCES public.estrategias(id_estrategia) ON DELETE CASCADE,
  id_cd INTEGER REFERENCES public.cenario_demanda(id_cd) ON DELETE CASCADE,
  id_cc INTEGER REFERENCES public.cenario_consumo(id_cc) ON DELETE CASCADE,
  id_cp INTEGER REFERENCES public.cenario_perdas(id_cp) ON DELETE CASCADE,
  volume_captado FLOAT,
  capex FLOAT,
  opex FLOAT,
  rebaixamento FLOAT,
  demanda FLOAT,
  perdas FLOAT
);

END $$;

-- Enable RLS and create open policies for authenticated users
ALTER TABLE public.fonte_agua ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.tipos_cenarios ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.cenarios ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.estrategias ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.simulacao_ssd ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.cenarios_fonte ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.estrategias_fonte ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.cenario_simulacao ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.cenario_demanda ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.cenario_consumo ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.cenario_perdas ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.dados_simulacao ENABLE ROW LEVEL SECURITY;

DO $$
DECLARE
  t text;
  tables text[] := ARRAY['fonte_agua', 'tipos_cenarios', 'cenarios', 'estrategias', 'simulacao_ssd', 'cenarios_fonte', 'estrategias_fonte', 'cenario_simulacao', 'cenario_demanda', 'cenario_consumo', 'cenario_perdas', 'dados_simulacao'];
BEGIN
  FOREACH t IN ARRAY tables LOOP
    EXECUTE format('DROP POLICY IF EXISTS "authenticated_all" ON public.%I', t);
    EXECUTE format('CREATE POLICY "authenticated_all" ON public.%I FOR ALL TO authenticated USING (true) WITH CHECK (true)', t);
    EXECUTE format('DROP POLICY IF EXISTS "anon_read" ON public.%I', t);
    EXECUTE format('CREATE POLICY "anon_read" ON public.%I FOR SELECT TO anon USING (true)', t);
  END LOOP;
END $$;
