CREATE TABLE IF NOT EXISTS public.tipo_cenario_cenario (
  id_tcc INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  id_tc INTEGER REFERENCES public.tipos_cenarios(id_tc) ON DELETE CASCADE,
  id_c INTEGER REFERENCES public.cenarios(id_cenarios) ON DELETE CASCADE
);

ALTER TABLE public.tipo_cenario_cenario ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "authenticated_all" ON public.tipo_cenario_cenario;
CREATE POLICY "authenticated_all" ON public.tipo_cenario_cenario
  FOR ALL TO authenticated USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "anon_read" ON public.tipo_cenario_cenario;
CREATE POLICY "anon_read" ON public.tipo_cenario_cenario
  FOR SELECT TO anon USING (true);
